version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-frontend
    ports:
      - "8000:8000"
    environment:
      FLASK_ENV: production
    depends_on:
      - mongo
    networks:
      - flask-network

  mongo:
    build:
      context: .
      dockerfile: Dockerfile-mongo
    container_name: flask-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - flask-network

volumes:
  mongodb_data:

networks:
  flask-network:
    driver: bridge
