version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      FLASK_ENV: production
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
